comments_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from comments.viewsets import MainPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainPageView.as_view(), name='home'),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/models.py
from django.contrib.auth.models import User
from django.db import models
from storages.backends.s3boto3 import S3Boto3Storage


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    email = models.EmailField()
    home_page = models.URLField(blank=True, null=True)
    text = models.TextField(blank=True)
    parent_comment = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


class UploadedFile(models.Model):
    file_path = models.FileField(storage=S3Boto3Storage(), upload_to='uploaded_files/')
    file_type = models.CharField(max_length=50)
    upload_date = models.DateTimeField(auto_now_add=True)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)


class CommentImage(models.Model):
    image_path = models.ImageField(storage=S3Boto3Storage(), upload_to='comment_images/')
    image_width = models.PositiveIntegerField()
    image_height = models.PositiveIntegerField()
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)


class HTMLTag(models.Model):
    tag_name = models.CharField(max_length=20)

comments/forms.py
from html.parser import HTMLParser

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
import bleach
from django import forms
from .models import Comment, HTMLTag
from django.core.validators import RegexValidator
from captcha.fields import CaptchaField


class CommentForm(forms.ModelForm):
    captcha = CaptchaField()
    attachment = forms.FileField(required=False)

    # username field validation
    username = forms.CharField(validators=[
        RegexValidator(r'^[a-zA-Z0-9]*$', message='Поле должно содержать только цифры и латинские буквы')])

    def validate_xhtml(self, text):
        class MyHTMLParser(HTMLParser):
            def __init__(self):
                super().__init__()
                self.open_tags = []

            def handle_starttag(self, tag, attrs):
                self.open_tags.append(tag)

            def handle_endtag(self, tag):
                if self.open_tags:
                    self.open_tags.pop()

        parser = MyHTMLParser()
        parser.feed(text)

        if parser.open_tags:
            raise ValidationError('Неверное закрытие тегов.')

        return text

    def clean_text(self):
        text = self.cleaned_data.get('text')
        allowed_tags = HTMLTag.objects.values_list('tag_name', flat=True)
        cleaned_text = bleach.clean(text, tags=allowed_tags, strip=True)

        if text != cleaned_text:
            # raise forms.ValidationError('Использованы недопустимые теги.')
            self.add_error(
                'text',
                forms.ValidationError("Использованы недопустимые теги")
            )

        self.validate_xhtml(cleaned_text)

        return cleaned_text

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        email = cleaned_data.get('email')

        if username and email:
            if User.objects.filter(username=username).exists() and not User.objects.filter(email=email).exists():
                self.add_error(
                    'username',
                    forms.ValidationError("Пользователь с таким username уже существует, но с таким email нет")
                )

            if not User.objects.filter(username=username).exists() and User.objects.filter(email=email).exists():
                self.add_error(
                    'email',
                    forms.ValidationError("Пользователь с таким email уже есть")
                )

        return cleaned_data

    class Meta:
        model = Comment
        fields = ['username', 'email', 'home_page', 'text', 'attachment', 'captcha', ]

comments/views.py
# from django.shortcuts import render

# Create your views here.

comments/templates/comments/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <title>{{title}}</title>
    <link rel="stylesheet" href="{% static 'comments/css/styles.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <script src="{% static 'comments/js/custom.js' %}"></script>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

comments/templates/comments/form_template.html
<form method="post" id="commentForm" enctype="multipart/form-data" style="display:none;">
    {% csrf_token %}
    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <button type="submit">Разместить</button>
</form>

comments/templates/comments/main_page_copy.html
{% extends 'comments/base.html' %}

{% block content %}
    <div class="form-container">
        <h1>{{ title }}</h1>
        <button id="showForm">Новая тема</button>
        {% include 'comments/form_template.html' %}
    </div>

    <div class="sorting-buttons">
        <button class="sort-button" data-column="username">Сортировать по Пользователю</button>
        <button class="sort-button" data-column="email">Сортировать по Email</button>
        <button class="sort-button" data-column="created_at">Сортировать по времени создания</button>
    </div>

    <div class="main-table">
        {% for comment in comments %}
            {% include 'comments/parent_comment.html' with comment=comment %}
        {% endfor %}
    </div>

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% else %}
                <span class="disabled">&laquo; first</span>
                <span class="disabled">previous</span>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% else %}
                <span class="disabled">next</span>
                <span class="disabled">last &raquo;</span>
            {% endif %}
        </span>
    </div>
{% endblock %}

comments/templates/comments/parent_comment.html
<div class="{% if comment.parent_comment %}child-comment{% else %}parent-comment{% endif %}">
    <div class="info">
        <div class="block-username"><strong>Пользователь:</strong> {{ comment.user.username }}</div>
        <div class="block-email"><strong>Email:</strong> {{ comment.user.email }}</div>
        <div class="block-created_at"><strong>Создано:</strong> {{ comment.created_at }}</div>
    </div>
    <div class="comment-text">
        {{ comment.text|safe }}
    </div>
    <div class="comment-files">
        {% for image in comment.commentimage_set.all %}
            {% with file_name=image.image_path.name|cut:"comment_images/" %}
                <a href="#" class="open-image-modal" data-original="{{ image.image_path.url }}">{{ file_name }}</a>
            {% endwith %}
        {% endfor %}
        {% for file in comment.uploadedfile_set.all %}
            {% with file_name=file.file_path.name|cut:"uploaded_files/" %}
                <a href="#" class="open-text-modal" data-original="{{ file.file_path.url }}">{{ file_name }}</a>
            {% endwith %}
        {% endfor %}
    </div>
    <button class="reply-button">Форма ответа</button>
    {% if comment.comment_set.all.exists %}
        <button class="show-children-button">Показать ветку</button>
    {% endif %}

    <div class="reply-form" style="display:none;">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for f in form %}
                <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }}</p>
                <div class="form-error">{{ f.errors }}</div>
            {% endfor %}
            <input type="hidden" name="parent_comment" value="{{ comment.id }}">
            <button type="submit">Отправить ответ</button>
        </form>
    </div>

    <div class="children-container" style="display:none;">
        {% for child_comment in comment.comment_set.all %}
            {% include 'comments/parent_comment.html' with comment=child_comment %}
        {% endfor %}
    </div>
</div>